 <style>

 a{
    font-weight: bold;
    font-size: 13px;
    font-family:‘Lucida Sans Unicode’, ‘Lucida Grande’, sans-serif;   
    color:#FFFFFF; 
    text-decoration:none;
    background:#00BCFF;
    padding-left: 5px;
    padding-right: 5px;
    border-style: groove #0000FF ;
    border-radius: 25px;}
 
 p{
    color:#0000FF;}

  form{
    margin-left:5%;
  }
  h1{
    color:#0000FF;
    margin-left:5%;
  }
    
  h2{

    color:#0000FF;
    font-size:15;
    font-weight: 10;
    

  }



  </style>
  <?php 
$this->title = "Agregar nuevo HW AXE";
$this->headTitle($this->title);

echo $this->form ;
?>
