<style>
   a{
    font-weight: bold;
    font-size: 13px;
    font-family:‘Lucida Sans Unicode’, ‘Lucida Grande’, sans-serif;   
    color:#FFFFFF; 
    text-decoration:none;
    background:#00BCFF;
    padding-left: 5px;
    padding-right: 5px;
    border-style: groove #0000FF ;
    border-radius: 25px;


  }
  p{

    color: blue;
    align-content: center;
    font-size:20px;
  }
</style>
<div class="container">
<p>DASHBOARD CORE VOZ</p></div>
<table>
<tr>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionar'));?>">NODO LTT</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodosrnc'));?>">NODO RNC</a></td>
  <td><a href="<?php echo $this->baseUrl(); ?>/hwccp">NODO HWCCP</a></td>
  <td><a href="<?php echo $this->baseUrl(); ?>/hwaxe">NODO HWAXE</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodospdi'));?>">PIDS ASIGNADOS</a></td>

</tr>
<tr>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodosbsc'));?>">NODO BSC</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodosmsc'));?>">NODO MSC</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodoshlr'));?>">NODO HLR</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarnodosmgw'));?>">NODO MGW</a></td>

  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarcredenciales'));?>">CREDENCIALES</a></td>
  <td><a href="<?php echo $this->url(array('controller'=>'index', 
        'action'=>'seleccionarubicacion'));?>">UBICACIONES</a></td>



</tr>



  <td></td>
  <td></td>
  </tr>
  <tr>
    
  </tr>
  
</table>