<style>
   a{
    font-weight: bold;
    font-size: 13px;
    font-family:‘Lucida Sans Unicode’, ‘Lucida Grande’, sans-serif;   
    color:#FFFFFF; 
    text-decoration:none;
    background:#00BCFF;
    padding-left: 5px;
    padding-right: 5px;
    border-style: groove #0000FF ;
    border-radius: 25px;


  }
  p{

    color: blue;
    align-content: center;
    font-size:20px;
  }
</style>
<table>
<tr>
  <td><a href="<?php echo $this->baseUrl(); ?>/viewnodosmsc">VISUALIZAR NODOS MSC</a></td>
  <td><a href="<?php echo $this->baseUrl(); ?>/nodosmsc">MANTENER NODOS MSC</a></td>
 </tr>
 </table>